from graphviz import Digraph

if __name__ == '__main__':
    dot = Digraph(comment='Модель выбора фреймворка для машинного обучения', format='png')
    dot.attr(rankdir='TB', ranksep='1', nodesep='0.5', size='8.27,11.69!', dpi='300', fontsize='12')

    dot.node('A', 'Выбор фреймворка', fontsize='14')
    dot.node('S1', 'Разработчик', fontsize='12')
    dot.node('S2', 'Менеджер проекта', fontsize='12')
    dot.node('S3', 'Исследователь', fontsize='12')
    dot.node('B', 'Производительность', fontsize='12')
    dot.node('C', 'Удобство использования', fontsize='12')
    dot.node('D', 'Сообщество и поддержка', fontsize='12')
    dot.node('E', 'Масштабируемость', fontsize='12')
    dot.node('F', 'Безопасность', fontsize='12')
    dot.node('G', 'TensorFlow', fontsize='12')
    dot.node('H', 'PyTorch', fontsize='12')
    dot.node('I', 'Keras', fontsize='12')
    dot.node('J', 'Scikit-learn', fontsize='12')

    dot.edge('A', 'S1')
    dot.edge('A', 'S2')
    dot.edge('A', 'S3')

    dot.edge('S1', 'B')
    dot.edge('S1', 'C')
    dot.edge('S1', 'D')
    dot.edge('S2', 'E')
    dot.edge('S2', 'F')
    dot.edge('S2', 'D')
    dot.edge('S3', 'B')
    dot.edge('S3', 'E')
    dot.edge('S3', 'C')

    dot.edge('B', 'G')
    dot.edge('B', 'H')
    dot.edge('B', 'I')
    dot.edge('B', 'J')
    dot.edge('C', 'G')
    dot.edge('C', 'H')
    dot.edge('C', 'I')
    dot.edge('C', 'J')
    dot.edge('D', 'G')
    dot.edge('D', 'H')
    dot.edge('D', 'I')
    dot.edge('D', 'J')
    dot.edge('E', 'G')
    dot.edge('E', 'H')
    dot.edge('E', 'I')
    dot.edge('E', 'J')
    dot.edge('F', 'G')
    dot.edge('F', 'H')
    dot.edge('F', 'I')
    dot.edge('F', 'J')

    dot.render('hierarchical_model', format='png', view=True)
